<?php

namespace App\Tests\Service;

use App\Model\Circle;
use App\Model\Triangle;
use App\Service\GeometryCalculator;
use PHPUnit\Framework\TestCase;

class GeometryCalculatorTest extends TestCase
{

    protected static Triangle $triangle;
    protected static Circle $circle;

    protected static GeometryCalculator $geometryCalculator;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$circle = new Circle(3);
        self::$triangle = new Triangle(3,4, 5);
        self::$geometryCalculator = new GeometryCalculator();
    }



    public function testCalculateSumOfAreas(){
        $sumOfAreas = self::$geometryCalculator->calculateSumOfAreas(self::$circle, self::$triangle);

        $this->assertEquals(34.27433388230814, $sumOfAreas);
    }

    public function testCalculateSumOfCircumference(){
        $sumOfAreas = self::$geometryCalculator->calculateSumOfCircumference(self::$circle, self::$triangle);

        $this->assertEquals(30.84955592153876, $sumOfAreas);
    }


}
