<?php

namespace App\Tests\Model;

use App\Model\Circle;
use PHPUnit\Framework\TestCase;

class CircleTest extends TestCase
{

    protected static Circle $circle;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$circle = new Circle(3);
    }


    public function testGetDiameter(): void
    {
        $this->assertEquals(6, self::$circle->getDiameter());
    }

    public function testGetCircumference(): void
    {
        $this->assertEquals(18.849555921539, self::$circle->getCircumference());
    }

    public function testGetSurface(): void
    {
        $this->assertEquals(28.274333882308, self::$circle->getSurface());
    }
}
