<?php

namespace App\Tests\Model;

use App\Model\Triangle;
use PHPUnit\Framework\TestCase;

class TriangleTest extends TestCase
{
    protected static Triangle $triangle;



    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$triangle = new Triangle(3,4, 5);
    }

    public function testGetCircumference(): void
    {
        $this->assertEquals(12, self::$triangle->getCircumference());
    }

    public function testGetSurface(): void
    {
        $this->assertEquals(6, self::$triangle->getSurface());
    }
}
